ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

ARDUINO_LIBS = Ethernet SPI SoftwareSerial

USER_LIB_PATH = /home/pi/Arduino/libraries
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
